name: personal_financial_manager
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter  
  charts_flutter: ^0.12.0
  fl_chart: ^0.65.0
  provider: ^6.0.5
  shared_preferences: ^2.1.0
  uuid: ^3.0.7
  intl: ^0.17.0
  path_provider: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/finance_data.json
    - assets/data/financial_goals.json
    - assets/data/forecast_transactions.json
    - assets/data/transaction_categories.json